stages:
  - image
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGEREF: $CI_REGISTRY/disciplinas1/mc426/projeto/base:latest

base image:
  tags:
    - docker
  stage: image
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGEREF .
    - docker push $IMAGEREF

build backend:
  stage: build
  image: $IMAGEREF
  script:
    - cd ./backend
    - swift build

test backend:
  stage: test
  image: $IMAGEREF
  script:
    - cd ./backend
    - swift test
