stages:
  - image
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGEREF: $CI_REGISTRY/disciplinas1/mc426/swiftpython:latest

before_script:
  - apt-get install -y ssh-client

dockerfile:
  tags:
    - docker
  stage: image
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGEREF .
    - docker push $IMAGEREF
